version: "3.8"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./server:/app
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      BASE_URL: ${BASE_URL}
    depends_on:
      - db
    networks:
      - shortener-network
  db:
    image: postgres:12
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - shortener-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '4000:5173'
    volumes:
      - ./client/src:/app/src
networks:
  shortener-network:
    driver: bridge
